name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      strategy:
        matrix:
          # Include amd64 on all platforms.
          goos: [windows, freebsd, openbsd, linux, dragonfly, darwin]
          goarch: [amd64, 386]
          exclude:
            # Exclude i386 on darwin and dragonfly.
            - goarch: 386
              goos: dragonfly
            - goarch: 386
              goos: darwin
          include:
            # BEIGIN MacOS ARM64
            - goos: darwin
              goarch: arm64
            # END MacOS ARM64
            # BEGIN Linux ARM 5 6 7
            - goos: linux
              goarch: arm
              goarm: 7
            - goos: linux
              goarch: arm
              goarm: 6
            - goos: linux
              goarch: arm
              goarm: 5
            # END Linux ARM 5 6 7
            # BEGIN Android ARM 8
            - goos: android
              goarch: arm64
            # END Android ARM 8
            # Windows ARM 7
            - goos: windows
              goarch: arm
              goarm: 7
            # BEGIN Other architectures
            # BEGIN riscv64 & ARM64
            - goos: linux
              goarch: arm64
            - goos: linux
              goarch: riscv64
            # END riscv64 & ARM64
            # BEGIN MIPS
            - goos: linux
              goarch: mips64
            - goos: linux
              goarch: mips64le
            - goos: linux
              goarch: mipsle
            - goos: linux
              goarch: mips
            # END MIPS
            # BEGIN PPC
            - goos: linux
              goarch: ppc64
            - goos: linux
              goarch: ppc64le
            # END PPC
            # BEGIN FreeBSD ARM
            - goos: freebsd
              goarch: arm64
            - goos: freebsd
              goarch: arm
              goarm: 7
            # END FreeBSD ARM
            # BEGIN S390X
            - goos: linux
              goarch: s390x
            # END S390X
            # END Other architectures
            # BEGIN OPENBSD ARM
            - goos: openbsd
              goarch: arm64
            - goos: openbsd
              goarch: arm
              goarm: 7
            # END OPENBSD ARM
        fail-fast: false
      
      runs-on: ubuntu-latest
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
        CGO_ENABLED: 0
      steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build main.go -o GoSeeder

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
